package errors

type ErrorCode int

const (
	// ? 1xx Informational
	Continue           ErrorCode = 100 // 100 - Continue (Won't retry)
	SwitchingProtocols ErrorCode = 101 // 101 - Switching Protocols (Won't retry)
	Processing         ErrorCode = 102 // 102 - Processing (Won't retry)
	EarlyHints         ErrorCode = 103 // 103 - Early Hints (Won't retry)

	// ? 2xx Success
	Success                     ErrorCode = 200 // 200 - Success (Won't retry)
	Created                     ErrorCode = 201 // 201 - Created (Won't retry)
	Accepted                    ErrorCode = 202 // 202 - Accepted (Won't retry)
	NonAuthoritativeInformation ErrorCode = 203 // 203 - Non-Authoritative Information (Won't retry)
	NoContent                   ErrorCode = 204 // 204 - No Content (Won't retry)
	ResetContent                ErrorCode = 205 // 205 - Reset Content (Won't retry)
	PartialContent              ErrorCode = 206 // 206 - Partial Content (Won't retry)
	MultiStatus                 ErrorCode = 207 // 207 - Multi-Status (Won't retry)
	AlreadyReported             ErrorCode = 208 // 208 - Already Reported (Won't retry)
	IMUsed                      ErrorCode = 226 // 226 - IM Used (Won't retry)

	// ? 4xx Client Error
	InvalidRequest              ErrorCode = 400 // 400 - Bad Request (Won't retry)
	Unauthorized                ErrorCode = 401 // 401 - Unauthorized (Won't retry)
	PaymentRequired             ErrorCode = 402 // 402 - Payment Required (Won't retry)
	Forbidden                   ErrorCode = 403 // 403 - Forbidden (Won't retry)
	NotFound                    ErrorCode = 404 // 404 - Not Found (Won't retry)
	MethodNotAllowed            ErrorCode = 405 // 405 - Method Not Allowed (Won't retry)
	NotAcceptable               ErrorCode = 406 // 406 - Not Acceptable (Won't retry)
	ProxyAuthenticationRequired ErrorCode = 407 // 407 - Proxy Authentication Required (Won't retry)
	RequestTimeout              ErrorCode = 408 // 408 - Request Timeout (Won't retry)
	Conflict                    ErrorCode = 409 // 409 - Conflict (Won't retry)
	Gone                        ErrorCode = 410 // 410 - Gone (Won't retry)
	LengthRequired              ErrorCode = 411 // 411 - Length Required (Won't retry)
	PreconditionFailed          ErrorCode = 412 // 412 - Precondition Failed (Won't retry)
	PayloadTooLarge             ErrorCode = 413 // 413 - Payload Too Large (Won't retry)
	URITooLong                  ErrorCode = 414 // 414 - URI Too Long (Won't retry)
	UnsupportedMediaType        ErrorCode = 415 // 415 - Unsupported Media Type (Won't retry)
	RangeNotSatisfiable         ErrorCode = 416 // 416 - Range Not Satisfiable (Won't retry)
	ExpectationFailed           ErrorCode = 417 // 417 - Expectation Failed (Won't retry)
	ImATeapot                   ErrorCode = 418 // 418 - I'm a teapot (Won't retry)
	MisdirectedRequest          ErrorCode = 421 // 421 - Misdirected Request (Won't retry)
	UnprocessableEntity         ErrorCode = 422 // 422 - Unprocessable Entity (Won't retry)
	Locked                      ErrorCode = 423 // 423 - Locked (Won't retry)
	FailedDependency            ErrorCode = 424 // 424 - Failed Dependency (Won't retry)
	TooEarly                    ErrorCode = 425 // 425 - Too Early (Won't retry)
	UpgradeRequired             ErrorCode = 426 // 426 - Upgrade Required (Won't retry)
	PreconditionRequired        ErrorCode = 428 // 428 - Precondition Required (Won't retry)
	TooManyRequests             ErrorCode = 429 // 429 - Too Many Requests (Won't retry)
	RequestHeaderFieldsTooLarge ErrorCode = 431 // 431 - Request Header Fields Too Large (Won't retry)
	UnavailableForLegalReasons  ErrorCode = 451 // 451 - Unavailable For Legal Reasons (Won't retry)

	// ? 5xx Server Error
	InternalServer                ErrorCode = 500 // 500 - Internal Server Error (Will retry)
	NotImplemented                ErrorCode = 501 // 501 - Not Implemented (Will retry)
	BadGateway                    ErrorCode = 502 // 502 - Bad Gateway (Will retry)
	ServiceUnavailable            ErrorCode = 503 // 503 - Service Unavailable (Will retry)
	GatewayTimeout                ErrorCode = 504 // 504 - Gateway Timeout (Will retry)
	HTTPVersionError              ErrorCode = 505 // 505 - HTTP Version Not Supported (Will retry)
	VariantAlsoNegotiates         ErrorCode = 506 // 506 - Variant Also Negotiates (Will retry)
	InsufficientStorage           ErrorCode = 507 // 507 - Insufficient Storage (Will retry)
	LoopDetected                  ErrorCode = 508 // 508 - Loop Detected (Will retry)
	NotExtended                   ErrorCode = 510 // 510 - Not Extended (Will retry)
	NetworkAuthenticationRequired ErrorCode = 511 // 511 - Network Authentication Required (Will retry)
)
