package cli

// CommandRegistry holds all available commands
var CommandRegistry = map[string]Command{
	"health": {
		Name:        "health",
		Description: "Check server health status",
		Method:      "GET",
		Endpoint:    "/health",
		ParamTypes:  []ParamType{},
		Example:     "./quiver health",
	},
	"list": {
		Name:        "list",
		Description: "List all packages",
		Method:      "GET", 
		Endpoint:    "/api/v1/packages",
		ParamTypes:  []ParamType{},
		Example:     "./quiver list",
	},
	"get": {
		Name:        "get",
		Description: "Get information about a specific package",
		Method:      "GET",
		Endpoint:    "/api/v1/packages/{id}",
		ParamTypes: []ParamType{
			{Name: "package_id", Type: "string", Required: true, Position: 0, URLParam: true},
		},
		Example: "./quiver get minecraft-server",
	},
	"start": {
		Name:        "start",
		Description: "Start a package (asynchronous - returns immediately)",
		Method:      "POST",
		Endpoint:    "/api/v1/packages/{id}/start",
		ParamTypes: []ParamType{
			{Name: "package_id", Type: "string", Required: true, Position: 0, URLParam: true},
		},
		Example: "./quiver start minecraft-server",
	},
	"stop": {
		Name:        "stop",
		Description: "Stop a package",
		Method:      "POST",
		Endpoint:    "/api/v1/packages/{id}/stop",
		ParamTypes: []ParamType{
			{Name: "package_id", Type: "string", Required: true, Position: 0, URLParam: true},
		},
		Example: "./quiver stop minecraft-server",
	},
	"processes": {
		Name:        "processes",
		Description: "Get running processes for a package",
		Method:      "GET",
		Endpoint:    "/api/v1/packages/{id}/processes",
		ParamTypes: []ParamType{
			{Name: "package_id", Type: "string", Required: true, Position: 0, URLParam: true},
		},
		Example: "./quiver processes minecraft-server",
	},
	"status": {
		Name:        "status",
		Description: "Get package status",
		Method:      "GET",
		Endpoint:    "/api/v1/packages/{id}/status",
		ParamTypes: []ParamType{
			{Name: "package_id", Type: "string", Required: true, Position: 0, URLParam: true},
		},
		Example: "./quiver status minecraft-server",
	},
	"start-status": {
		Name:        "start-status",
		Description: "Get execution status of a started package",
		Method:      "GET",
		Endpoint:    "/api/v1/packages/{id}/execution/status",
		ParamTypes: []ParamType{
			{Name: "package_id", Type: "string", Required: true, Position: 0, URLParam: true},
		},
		Example: "./quiver start-status minecraft-server",
	},
	"all-executions": {
		Name:        "all-executions",
		Description: "List all package execution statuses",
		Method:      "GET",
		Endpoint:    "/api/v1/packages/executions/status",
		ParamTypes:  []ParamType{},
		Example:     "./quiver all-executions",
	},
	"info": {
		Name:        "info",
		Description: "Get server information",
		Method:      "GET",
		Endpoint:    "/api/v1/server/info",
		ParamTypes:  []ParamType{},
		Example:     "./quiver info",
	},
	"server-status": {
		Name:        "server-status",
		Description: "Get server status",
		Method:      "GET",
		Endpoint:    "/api/v1/server/status",
		ParamTypes:  []ParamType{},
		Example:     "./quiver server-status",
	},
	// Arrow package management commands
	"search": {
		Name:        "search",
		Description: "Search for arrows in repositories",
		Method:      "GET",
		Endpoint:    "/api/v1/arrows/search",
		ParamTypes: []ParamType{
			{Name: "query", Type: "string", Required: false, Position: 0, URLParam: false},
		},
		Example: "./quiver search minecraft",
	},
	"install": {
		Name:        "install",
		Description: "Install an arrow",
		Method:      "POST",
		Endpoint:    "/api/v1/arrows/{name}/install",
		ParamTypes: []ParamType{
			{Name: "name", Type: "string", Required: true, Position: 0, URLParam: true},
		},
		Example: "./quiver install cs2",
	},
	"execute": {
		Name:        "execute",
		Description: "Execute an installed arrow (asynchronous - returns immediately)",
		Method:      "POST",
		Endpoint:    "/api/v1/arrows/{name}/execute",
		ParamTypes: []ParamType{
			{Name: "name", Type: "string", Required: true, Position: 0, URLParam: true},
		},
		Example: "./quiver execute cs2",
	},
	"execution-status": {
		Name:        "execution-status",
		Description: "Get execution status of an arrow",
		Method:      "GET",
		Endpoint:    "/api/v1/arrows/{name}/execution/status",
		ParamTypes: []ParamType{
			{Name: "name", Type: "string", Required: true, Position: 0, URLParam: true},
		},
		Example: "./quiver execution-status cs2",
	},
	"executions": {
		Name:        "executions",
		Description: "List all execution statuses",
		Method:      "GET",
		Endpoint:    "/api/v1/arrows/executions/status",
		ParamTypes:  []ParamType{},
		Example:     "./quiver executions",
	},
	"uninstall": {
		Name:        "uninstall",
		Description: "Uninstall an arrow",
		Method:      "DELETE",
		Endpoint:    "/api/v1/arrows/{name}/uninstall",
		ParamTypes: []ParamType{
			{Name: "name", Type: "string", Required: true, Position: 0, URLParam: true},
		},
		Example: "./quiver uninstall cs2",
	},
	"update": {
		Name:        "update",
		Description: "Update an arrow to the latest version",
		Method:      "PUT",
		Endpoint:    "/api/v1/arrows/{name}/update",
		ParamTypes: []ParamType{
			{Name: "name", Type: "string", Required: true, Position: 0, URLParam: true},
		},
		Example: "./quiver update cs2",
	},
	"validate": {
		Name:        "validate",
		Description: "Validate an arrow installation",
		Method:      "POST",
		Endpoint:    "/api/v1/arrows/{name}/validate",
		ParamTypes: []ParamType{
			{Name: "name", Type: "string", Required: true, Position: 0, URLParam: true},
		},
		Example: "./quiver validate cs2",
	},
	"installed": {
		Name:        "installed",
		Description: "List all installed arrows",
		Method:      "GET",
		Endpoint:    "/api/v1/arrows/installed",
		ParamTypes:  []ParamType{},
		Example:     "./quiver installed",
	},
	"arrow-status": {
		Name:        "arrow-status",
		Description: "Get arrow installation status",
		Method:      "GET",
		Endpoint:    "/api/v1/arrows/{name}/status",
		ParamTypes: []ParamType{
			{Name: "name", Type: "string", Required: true, Position: 0, URLParam: true},
		},
		Example: "./quiver arrow-status cs2",
	},
	"repo": {
		Name:        "repo",
		Description: "Manage repositories",
		Method:      "GET",
		Endpoint:    "/api/v1/repositories",
		ParamTypes:  []ParamType{},
		Example:     "./quiver repo list",
		Subcommands: map[string]Command{
			"list": {
				Name:        "list",
				Description: "List all repositories",
				Method:      "GET",
				Endpoint:    "/api/v1/repositories",
				ParamTypes:  []ParamType{},
				Example:     "./quiver repo list",
			},
			"add": {
				Name:        "add",
				Description: "Add a new repository",
				Method:      "POST",
				Endpoint:    "/api/v1/repositories",
				ParamTypes: []ParamType{
					{Name: "repository", Type: "string", Required: true, Position: 0, URLParam: false},
				},
				Example: "./quiver repo add https://github.com/example/arrows",
			},
			"remove": {
				Name:        "remove",
				Description: "Remove a repository",
				Method:      "DELETE",
				Endpoint:    "/api/v1/repositories",
				ParamTypes: []ParamType{
					{Name: "repository", Type: "string", Required: true, Position: 0, URLParam: false},
				},
				Example: "./quiver repo remove https://github.com/example/arrows",
			},
		},
	},
	"netbridge": {
		Name:        "netbridge",
		Description: "Manage network port forwarding",
		Method:      "GET",
		Endpoint:    "/api/v1/netbridge/status",
		ParamTypes:  []ParamType{},
		Example:     "./quiver netbridge status",
		Subcommands: map[string]Command{
			"open": {
				Name:        "open",
				Description: "Open a port for forwarding (supports auto-discovery)",
				Method:      "POST",
				Endpoint:    "/api/v1/netbridge/open/{port}/{protocol}",
				ParamTypes:  []ParamType{},
				Example:     "./quiver netbridge open 443 tcp OR ./quiver netbridge open tcp",
			},
			"close": {
				Name:        "close",
				Description: "Close a forwarded port",
				Method:      "POST",
				Endpoint:    "/api/v1/netbridge/close/{port}/{protocol}",
				ParamTypes:  []ParamType{},
				Example:     "./quiver netbridge close 443 tcp",
			},
			"list": {
				Name:        "list",
				Description: "List all open ports",
				Method:      "GET",
				Endpoint:    "/api/v1/netbridge/ports",
				ParamTypes:  []ParamType{},
				Example:     "./quiver netbridge list",
			},
			"ports": {
				Name:        "ports",
				Description: "List all open ports (alias for list)",
				Method:      "GET",
				Endpoint:    "/api/v1/netbridge/ports",
				ParamTypes:  []ParamType{},
				Example:     "./quiver netbridge ports",
			},
			"status": {
				Name:        "status",
				Description: "Show netbridge status and public IP",
				Method:      "GET",
				Endpoint:    "/api/v1/netbridge/status",
				ParamTypes:  []ParamType{},
				Example:     "./quiver netbridge status",
			},
			"refresh": {
				Name:        "refresh",
				Description: "Refresh public IP information",
				Method:      "POST",
				Endpoint:    "/api/v1/netbridge/refresh-ip",
				ParamTypes:  []ParamType{},
				Example:     "./quiver netbridge refresh",
			},
			"refresh-ip": {
				Name:        "refresh-ip",
				Description: "Refresh public IP information (alias for refresh)",
				Method:      "POST",
				Endpoint:    "/api/v1/netbridge/refresh-ip",
				ParamTypes:  []ParamType{},
				Example:     "./quiver netbridge refresh-ip",
			},
		},
	},
}
